/* WARNING: This file was automatically generated by lua2c. */

#ifdef __cplusplus
extern "C" {
#endif
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#ifdef __cplusplus
}
#endif
#include <stdio.h>
#include <stdlib.h>


#include <string.h>


#include <assert.h>

/* name: (main)
 * function(...) */
static int lcf_hello_main (lua_State * L) {
  enum { lc_nformalargs = 0 };
  #ifndef NDEBUG
  const int lc_nactualargs = lua_gettop(L);
  #endif
  #ifndef NDEBUG
  const int lc_nextra = (lc_nactualargs - lc_nformalargs);
  #endif
  
  /* -- the first program in every language
   * io.write("Hello world, from ",_VERSION,"!\n") */
  lua_getfield(L,LUA_ENVIRONINDEX,"io");
  lua_pushliteral(L,"write");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"Hello world, from ");
  lua_getfield(L,LUA_ENVIRONINDEX,"_VERSION");
  lua_pushliteral(L,"!\n");
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  return 0;
}


/* from lua.c */
/* create global arg table */

/* Lua module entry point */
int luaopen_hello(lua_State *L) {
  /* 注册模块函数 */
  lua_register(L, "hello", lcf_hello_main);
  
  /* 返回 1 表示返回一个值（模块表） */
  return 1;
}
