/* WARNING: This file was automatically generated by lua2c. */

#ifdef __cplusplus
extern "C" {
#endif
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#ifdef __cplusplus
}
#endif
#include <stdio.h>
#include <stdlib.h>


#include <string.h>


#include <assert.h>

/* name: (main)
 * function(...) */
static int lcf_hello_main (lua_State * L) {
  enum { lc_nformalargs = 0 };
  #ifndef NDEBUG
  const int lc_nactualargs = lua_gettop(L);
  #endif
  #ifndef NDEBUG
  const int lc_nextra = (lc_nactualargs - lc_nformalargs);
  #endif
  
  /* -- the first program in every language
   * require[[io]] */
  lua_getfield(L,LUA_GLOBALSINDEX,"require");
  lua_pushliteral(L,"io");
  lua_call(L,1,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  
  /* io.write("Hello world, from ",_VERSION,"!\n") */
  lua_getfield(L,LUA_GLOBALSINDEX,"io");
  lua_pushliteral(L,"write");
  lua_gettable(L,-2);
  lua_remove(L,-2);
  lua_pushliteral(L,"Hello world, from ");
  lua_getfield(L,LUA_GLOBALSINDEX,"_VERSION");
  lua_pushliteral(L,"!\n");
  lua_call(L,3,0);
  assert(lua_gettop(L) - lc_nextra == 0);
  return 0;
}


/* from lua.c */
/* create global arg table */

/* Lua module entry point - 自动执行版本 */
int luaopen_hello(lua_State *L) {
  /* 创建模块表 */
  lua_newtable(L);
  
  /* 立即执行原 Lua 脚本的主功能 */
  lua_pushcfunction(L, lcf_hello_main);
  if (lua_pcall(L, 0, 0, 0) != 0) {
    /* 错误处理 */
    lua_error(L);
  }
  
  /* 将主函数注册为模块表的一个字段（可选） */
  lua_pushcfunction(L, lcf_hello_main);
  lua_setfield(L, -2, "hello");
  
  /* 返回模块表 */
  return 1;
}
